# Generated by Django 3.0.9 on 2020-11-18 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usernameIG', models.CharField(max_length=50)),
                ('passwordIG', models.CharField(max_length=50)),
                ('followers', models.TextField()),
            ],
        ),
    ]
