# Generated by Django 3.0.9 on 2020-11-22 12:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('follower', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=30)),
                ('date', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), null=True, size=30)),
            ],
        ),
    ]
